# Generated by Django 4.1.1 on 2022-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doob_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(max_length=20)),
                ('Title2', models.CharField(max_length=20)),
                ('Title3', models.CharField(max_length=20)),
            ],
        ),
    ]
