# Generated by Django 4.1.1 on 2022-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doob_app', '0002_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
