# Generated by Django 4.1.1 on 2022-10-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doob_app', '0003_delete_title_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
