# Generated by Django 4.1.1 on 2022-10-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doob_app', '0007_profile_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_time',
        ),
    ]
